apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app
    tag: pyapp
  name: python-app
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-app
    tag: pyapp
  type: ClusterIP
