apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld
    tag: pythonhelloworld
  name: python-helloworld
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-helloworld
    tag: pythonhelloworld
  type: ClusterIP
