##  Named of the workflow.
name: show dir
## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository
on: [push]
## List the steps to be executed by the workflow

jobs:
  ## Set the name of the job
  show-dirs:
    ## Configure the operating system the workflow should run on.
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
    ## Define a sequence of steps to be executed ${{[ls, python --version]}}
    strategy:
      matrix:
        commands: [ls -la, git config --global user.name "mahmoud", git fetch, git pull origin main, git add .,git branch staging]
    steps:
      ## Use the public `checkout` actoin  in version v2  
      ## to checkout the existing code in the repository
      - uses: actions/checkout@v2
      ## Use the public `setup-python` action  in version v2  
      ## Executes the `python --version` command
      - run: ${{matrix.commands}}
